### ISSUE TITLE
Can't build dumb version

### ISSUE THREAD

**Issue by the-maldridge** [DavidGriffith/frotz#21]
I'm attempting to compile the dumb version for use with grue, and I'm running into this error:

```
src/dumb/dumb_input.c:82:13: error: conflicting types for ‘getline’
In file included from src/dumb/../common/frotz.h:29:0,
                 from src/dumb/dumb_frotz.h:9,
                 from src/dumb/dumb_input.c:7:
/usr/include/stdio.h:671:20: note: previous declaration of ‘getline’ was here
make: *** [src/dumb/dumb_input.o] Error 1
```

This is on Debian 7 with the provided Makefile.

**Comment by DavidGriffith** [comment]
I get this error message when trying to compile the dumb version of 2.43.  I don't get it with 2.44 or master.  Do you specifically need 2.43 for Grue?

**Comment by the-maldridge** [comment]
No, It was the recommended version but it seems to work fine with 2.44.

**Comment by DavidGriffith** [comment]
What "Grue" are you referring to?  Gruelang perhaps?

**Comment by the-maldridge** [comment]
Grue is a bot that sits in IRC and allows you to play frotz compatible games as a group.
